### ISSUE TITLE
Right click on anything (current file, treeview) seems to throw this error

### ISSUE THREAD

**Issue by keevan** [andremov/atom-themed-context-menu#14]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 20.04.3
**Thrown From**: [themed-context-menu](https://github.com/andremov/atom-themed-context-menu) package 0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'includes' of undefined

```
At /home/currentuser/.atom/packages/themed-context-menu/dist/themed-context-menu.js:1

TypeError: Cannot read property 'includes' of undefined
    at /packages/themed-context-menu/dist/themed-context-menu.js:1:4475
    at Array.filter (<anonymous>)
    at /packages/themed-context-menu/dist/themed-context-menu.js:1:4444)
    at /packages/themed-context-menu/dist/themed-context-menu.js:1:7649
```

### Commands

```
     -0:14.5.0 typescript:activate (atom-workspace.workspace.scrollbars-visible-always)
     -0:05.3.0 application:new-file (atom-pane.pane.active)
```

### Non-Core Packages

```
aligner 1.3.0 
aligner-javascript 1.3.0 
aligner-php 1.3.0 
atom-attribute-sorter 0.1.1 
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-debug-ui 1.0.4 
atom-hot-package-loader 0.5.1 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-debugger 0.0.3 
atom-ide-definitions 0.4.2 
atom-ide-deno 1.13.0 
atom-ide-hyperclick 1.0.11 
atom-ide-javascript 1.5.0 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-ide-ui 0.13.0 
atom-increment 0.3.4 
atom-inline-blame 0.0.10 
atom-keyboard-macros-vim 0.1.6 
atom-linter-phpstan 2.2.0 
atom-minify 0.8.0 
atom-path-intellisense 1.2.2 
atom-typescript 14.4.0 
autocomplete-emojis 2.5.0 
autocomplete-javascript 0.0.2 
autocomplete-paths 2.17.0 
autocomplete-sql 0.5.0 
better-jellybeans-syntax 1.1.0 
blame 1.2.0 
block-comment-plus 0.5.1 
busy-signal 2.0.1 
choose-pane 0.8.0 
context-menu-remove 0.2.1 
css-declaration-sorter 2.0.0 
cursor-history 0.14.0 
date-plus 1.2.0 
demo-mode 0.4.1 
disable-arrow-keys 0.1.0 
disable-keybindings 0.6.0 
docs-snippets 0.8.0 
double-tag 1.7.0 
dracula-syntax 3.0.2 
editorconfig 2.6.1 
emmet 2.4.3 
ex-mode 0.18.0 
file-icons 2.1.47 
gherkin-snippets 0.3.0 
git-line 0.6.0 
git-link 0.4.0 
git-time-machine 2.1.0 
goto-definition 1.3.4 
html-to-javascript 0.2.0 
ide-html 0.7.0 
ide-intelephense-forked 0.7.3 
ide-json 0.2.1 
ide-php 0.7.18 
indent-guide-improved 1.4.13 
inline-git-diff 2.4.0 
intentions 2.1.1 
javascript-drag-import 0.1.13 
keystroke 0.4.0 
language-babel 2.85.0 
language-blade 0.46.0 
language-crontab 1.0.0 
language-docker 1.1.8 
language-flight-manual 0.0.0 
language-gherkin 1.0.4 
language-ini 1.25.0 
language-javascript-jsx 0.3.7 
language-markdown 0.37.0 
language-nginx 0.8.0 
language-pgsql 0.2.3 
language-proto 0.8.0 
language-regexp 1.2.0 
language-sql-mysql 0.3.1 
lazy-motion 0.7.0 
lines 0.13.1 
linter 3.4.0 
linter-eslint 9.0.0 
linter-phpcs 1.8.1 
linter-spell 0.15.0 
linter-spell-javascript 0.9.0 
linter-ui-default 3.4.1 
linter-ui-plus 0.3.2 
linter-write-good 0.9.3 
min-ui 0.0.4 
minimap 4.40.0 
narrow 0.65.2 
one-dark-regex-syntax 1.2.1 
open-package 0.0.0 
open-this 0.5.0 
paner 1.0.0 
path-copy 0.14.0 
pen-paper-coffee-syntax 0.17.0 
pg-formatter 0.0.1 
php-composer-completion 0.3.4 
php-cs-fixer 4.3.0 
php-debug 0.3.5 
php-ide-serenata 5.4.1 
phpunit 1.2.0 
prettier-atom 0.60.1 
project-manager 3.3.8 
pure-syntax 2.0.0 
python-linters 0.0.5 
react 0.18.0 
react-snippets 2.0.0 
redux-snippets 0.2.2 
relative-numbers 0.9.1 
sass-autocompile 0.13.5 
smart-tab-name 1.0.5 
sort-lines 0.19.0 
split-diff 1.6.1 
stream-censor 0.3.0 
TabNine 4.0.7 
tester 1.4.0 
tester-phpunit 1.0.6 
themed-context-menu 0.3.0 
tidy-markdown 3.0.1 
toggle-packages 1.1.0 
toggle-quotes 1.1.4 
toggler 0.3.1 
vim-mode-plus 1.36.7 
vim-mode-plus-exchange 0.4.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
xatom-debug-php 0.1.3 
zentabs 0.8.9 
```

**Comment by andremov** [comment]
Hey! Seems like a problem with commands from other packages. Try with v0.3.2 if the issue is fixed.

**Comment by keevan** [comment]
Tried again, noticed a filter option which wasn't shown in the readme's GIF. Hoping there's an option to turn that off since it's buggy.

Anyways the menu appears but hovering over the "Split pane" submenu throws another error. I'll create a separate issue.

**Comment by keevan** [comment]
That said I'll close this issue since the immediate issue of opening the view itself appears fixed.

Thanks for the prompt resolution!
