### ISSUE TITLE
Uncaught TypeError: Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by 73** [andremov/atom-themed-context-menu#7]
### Steps to reproduce:

1. I clicked on file path in the status bar.

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.10
**Thrown From**: [themed-context-menu](https://github.com/andremov/atom-themed-context-menu) package 0.2.4

### Stack Trace

Uncaught TypeError: Reduce of empty array with no initial value

```
At /home/73/.atom/packages/themed-context-menu/dist/themed-context-menu.js:1

TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at u.getHeight (/packages/themed-context-menu/dist/themed-context-menu.js:1:3255)
    at u.getPositionStyleString (/packages/themed-context-menu/dist/themed-context-menu.js:1:2970)
    at /packages/themed-context-menu/dist/themed-context-menu.js:1:2537)
    at c.displayContextMenu (/packages/themed-context-menu/dist/themed-context-menu.js:1:3880)
    at ContextMenuManager.e.showForEvent (/packages/themed-context-menu/dist/themed-context-menu.js:1:3728)
    at WindowEventHandler.handleDocumentContextmenu (/usr/share/atom/resources/app/static/<embedded>:11:287456)
```

### Commands

```
     -4:10.4.0 intentions:highlight (input.hidden-input)
     -4:10.3.0 core:copy (input.hidden-input)
  2x -0:55.9.0 core:move-up (input.hidden-input)
     -0:54.6.0 core:move-down (input.hidden-input)
  3x -0:54.4.0 core:move-left (input.hidden-input)
     -0:53.8.0 core:backspace (input.hidden-input)
     -0:52.2.0 core:delete (input.hidden-input)
     -0:51.5.0 core:move-down (input.hidden-input)
  7x -0:48.3.0 core:backspace (input.hidden-input)
     -0:34.7.0 intentions:highlight (input.hidden-input)
     -0:34.7.0 core:paste (input.hidden-input)
     -0:33.2.0 core:move-down (input.hidden-input)
     -0:32.5.0 intentions:highlight (input.hidden-input)
     -0:32.4.0 core:save (input.hidden-input)
     -0:28.5.0 intentions:highlight (input.hidden-input)
     -0:28.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
adwaita-dark-ui 0.0.1 
atom-animations 0.1.0 
atom-hide-tabs 0.3.1 
atom-ide-outline 2.0.0 
atom-invisible-space 1.0.3 
atom-limelight 0.1.3 
atom-xcode-bigsur-syntax 0.6.0 
autocomplete-latex-references 0.3.2 
autocorrect 0.1.0 
autocorrect-en 0.0.3 
busy-signal 2.0.1 
cursor-blink-interval 0.3.1 
cursor-history 0.14.0 
custom-invisibles 0.1.2 
dbclick-tree-view 1.6.3 
document-outline 2.1.2 
expand-region 0.5.0 
fancy-bracket-matcher 2.1.0 
file-icons 2.1.47 
git-blame 1.8.0 
glowing-cursor 0.1.2 
gtk-dark-theme 0.1.4 
highlight-selected 0.17.0 
ide-css 0.3.5 
intentions 1.1.5 
jumpy 5.0.2 
language-docker 1.1.8 
language-ini 1.23.0 
language-latex 1.2.0 
language-markdown 0.37.0 
latex 0.50.2 
linter 3.3.0 
linter-shellcheck 1.6.0 
linter-textidote 1.0.0 
linter-ui-default 3.3.0 
monkey-jump 1.0.1 
navigation-pane 0.0.4 
neon-selection 0.3.2 
open-files 0.8.4 
open-terminal-here 2.3.2 
open-unsupported-files 1.0.20 
pigments 0.40.6 
rainbow-csv 1.4.0 
relative-numbers 0.9.1 
ruby-block 0.3.6 
scroll-fade 1.0.0 
split-diff 1.6.1 
themed-context-menu 0.2.4 
todo-show 2.3.2 
typewriter-scroll 1.0.2 
Zen-plus 1.1.0 
```

**Comment by andremov** [comment]
fixed, thanks for the feedback
